### ISSUE TITLE
提交结果以后，能否更新？

### ISSUE THREAD

**Issue by web199195** [thu-coai/SafetyBench#3]
https://llmbench.ai/align
您好，试着提交过safetybench的结果，但是发现提交后，只有一个结果，没法更新到榜单上。榜单上的结果都是9/1号的。这块后续提交结果后，能自动更新吗？

**Comment by nonstopfor** [comment]
目前的设定是如果想要在榜单上公开结果，需要在提交界面填写一个问卷，如下图所示：
<img width="1465" alt="image" src="https://github.com/thu-coai/SafetyBench/assets/47969037/27146886-c6c8-4ffd-b3f2-f0e2e475e976">

**Comment by web199195** [comment]
我们最近试着提交了下，发现没法提交了，是因为在维护吗？预计什么时候开始，能再次提交结果进行评测啊？

**Comment by nonstopfor** [comment]
> 我们最近试着提交了下，发现没法提交了，是因为在维护吗？预计什么时候开始，能再次提交结果进行评测啊？

现在应该可以了，之前是重启了一下服务器
