### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by HuTongxin** [thu-coai/SafetyBench#5]
我在Leaderboard上提交时由于上传文件失败，没有得到有效的测试结果。然而已显示超过了最大提交次数（大于5次上传文件失败），请问有什么解决方法吗？

**Comment by nonstopfor** [comment]
> 我在Leaderboard上提交时由于上传文件失败，没有得到有效的测试结果。然而已显示超过了最大提交次数（大于5次上传文件失败），请问有什么解决方法吗？

每天会重置这个次数～ 前几天服务器重启了一次，现在应该可以正常评测了
