### ISSUE TITLE
leaderboard 似乎不能登入?

### ISSUE THREAD

**Issue by FarnHua** [thu-coai/SafetyBench#7]
最近想上傳到safetybench看分數，但一直沒辦法登入，可以幫忙確認一下嗎? 不確定是不是我這邊的問題

**Comment by jlhe2000** [comment]
遇到了同样的问题

**Comment by LuoZhhh** [comment]
I can not register for the website (can not send the verification code to my email). Does anyone face the same issues?

**Comment by XWang20** [comment]
同样的问题，请问什么时候能够修复呢？

**Comment by nonstopfor** [comment]
很抱歉带来不便。这个问题已经修复。
Sorry for the inconvenience. The issue has been fixed.
